### ISSUE TITLE
Use Github as download "source"?

### ISSUE THREAD

**Issue by aprakasa** [thomasgriffin/TGM-Plugin-Activation#107]
Is it possible to use Github as the download <code>source</code> (for non-WordPress repository)? If yes, how?
I have try this but didnt work:

<pre>
array(
    'name'                  => 'Download From Github',
    'slug'                  => 'download-from-github',
    'source'                => 'https://github.com/SomeDude/download-from-github/archive/master.zip',
    'required'              => false,
    'version'               => '1.0',
    'force_activation'      => false,
    'force_deactivation'    => false,
    'external_url'          => 'https://github.com/SomeDude/download-from-github',
)
</pre>

and this:

<pre>'source'   => 'https://nodeload.github.com/SomeDude/download-from-github/zip/master'</pre>

Thanks

**Comment by jrfnl** [comment]
@aryaprakasa For GitHub repositories which have their code in the repo root (not in a /src subdirectory or something), this should now be possible once PR #327 has been merged.

Use `https://github.com/SomeDude/download-from-github/archive/master.zip` as source or point to a release zip.
