### ISSUE TITLE
Make a composer package

### ISSUE THREAD

**Issue by danielmartins** [thomasgriffin/TGM-Plugin-Activation#112]
It would be nice if this package can be installed via [composer](http://getcomposer.org/).

I think the wordpress developers community is adopting more and more the [composer](http://getcomposer.org/) to manage dependency. 

For example if i want to make my theme to receive future updates of TGM-Plugin-Activation with minimum efforts, today I declare TGM-Plugin-Activation as Sub-repository and freezes on a specific version that I'll use to develop. And if the TGM-Plugin-Activation updates and release a new version, I can just update my Sub-repository to the new version, make tests and add something if necessary.

I already use composer to manage some of dependencies of my themes and I thing that is more elegant and less overhead than make this dependencies as sub-repositories. 

I think the main benefits are:
- Automatic version updates(eg, 2._) - always grab the lastest version on branch 2._
- Easily add or remove deps

This structured package match why composer shines on as php dependecy manager. 

If you have interest and no one is already working on, I can make this package.

**Comment by GaryJones** [comment]
Folks,

Going forwards, the new package will be named per the new organisation: https://packagist.org/packages/tgmpa/tgm-plugin-activation .

The [old package](https://packagist.org/packages/tgm/plugin-activation) has been marked as abandoned and recommends the new package.
