### ISSUE TITLE
Strict Standards notices

### ISSUE THREAD

**Issue by rilwis** [thomasgriffin/TGM-Plugin-Activation#151]
Hi,

When I access the admin area, I see 2 lines of notices:

```
Strict Standards: Declaration of TGM_Bulk_Installer_Skin::before() should be compatible with Bulk_Upgrader_Skin::before($title = '') in /wp-content/themes/xxx/inc/class-tgm-plugin-activation.php on line 1893

Strict Standards: Declaration of TGM_Bulk_Installer_Skin::after() should be compatible with Bulk_Upgrader_Skin::after($title = '') in /wp-content/themes/xxx/inc/class-tgm-plugin-activation.php on line 1893
```

The fix is quite easy:

In line 1977, change:

``` php
public function before() {
```

to

``` php
public function before( $title = '' ) {
```

And In line 1999, change:

``` php
public function after() {
```

to

``` php
public function after( $title = '' ) {
```

I'm using PHP 5.4, WP 3.7.

**Comment by chill047** [comment]
Thanks alot.. It works like a charm ..

**Comment by jrfnl** [comment]
@rahulkashyapknl and @chill047 Not sure what version you are using, but this fix has been included in the library since v2.4.0. I suggest you upgrade rather than manually change it.

**Comment by e11world** [comment]
@rilwis Thanks for the solution. It fixed my issue.

**Comment by jrfnl** [comment]
@e11world Sorry, but are you suggesting that you are still using TGMPA < 2.4.0 ? If so, please do yourself and your users a favour and upgrade to the current version asap.

http://tgmpluginactivation.com/download/

**Comment by e11world** [comment]
@jrfnl I would be it isn't really up to me. I will keep it in mind.

**Comment by jrfnl** [comment]
@e11world In that case, _please_ contact the author of the plugin or theme which includes TGMPA in your site and ask them to upgrade. You'd do yourself and the other users of that plugin/theme a **big** favour! :+1:

**Comment by Mickey0001** [comment]
I had an older version of Betheme, thanks for the solution it worked like a charm.

**Comment by NTGsupport** [comment]
Thank you, Works for me too.

**Comment by sabur7** [comment]
Thanks. Worked for me also.

**Comment by vascofialho-nl** [comment]
it's been 10 years since this post started. 
I've used this solution today on "Skylab" theme and it worked like a charm. 

thank you.
