### ISSUE TITLE
WordPress 3.8 

### ISSUE THREAD

**Issue by ifkas** [thomasgriffin/TGM-Plugin-Activation#156]
It does not Activate installed plugins.

It was all good till 3.8 come out, so was testing it and simply doesn't do anything. I recorded video for it showing the behaviour

Link for the video: http://screenr.com/qX9H

**Comment by ramazan70** [comment]
themes/multinews/framework/class-tgm-plugin-activation.php on line 965

please help me

**Comment by jrfnl** [comment]
@ramazan70 This issues has been solved for years already. If you are running into it - ask the author of your theme to update the version of TGMPA they include with the theme.

**Comment by ramazan70** [comment]
thank you
