### ISSUE TITLE
TGM_Bulk_Installer missing

### ISSUE THREAD

**Issue by ctalkington** [thomasgriffin/TGM-Plugin-Activation#185]
I'm getting the following when trying to bulk install with v2.4.0. Haven't done much research on the issue but wanted to post it. One-off installs work fine.

>PHP Fatal error:  Class 'TGM_Bulk_Installer' not found in lib/class-tgm-plugin-activation.php on line 1579

WP 3.8.1 / PHP 5.4.26

**Comment by fk** [comment]
@thomasgriffin As far as I understand the fix has not made it into master yet?!

**Comment by Anydog** [comment]
It seems fix is not there yet ... I have same issue with 2.4.0 ...
So I switched back to 2.3.6 ...  :(

**Comment by matyushen** [comment]
Same here with 2.4.0

**Comment by yohnjang** [comment]
Still getting this error as well.  But, it's nice to know you can install each plug in individually.

**Comment by dingo-d** [comment]
Any info on the fix for this issue? Or is the fix to install each plugin separately?

**Comment by GaryJones** [comment]
Re-opening, as this isn't apprently fixed.

**Comment by GaryJones** [comment]
https://github.com/thomasgriffin/TGM-Plugin-Activation/commit/1e98e425f4a3bc43bd0fa05fe74a4268aa624f33 fixed this in the `develop` branch.

**Comment by pavot** [comment]
@GaryJones 

Still having: 
**Fatal error: Class 'TGM_Bulk_Installer' not found in /srv/users/*****/inc/plugins-integration/class-tgmpa.php on line 1781**

What ever branch master/develop I use. What ever I use for **'menu' => 'tgmpa-install-plugins',**

Can anyone, please, let me know what way to debug it?

**Comment by pavot** [comment]
Just found that **id** key in $config array cause the problem. Removed the **id** completely and all works now.

$config = array(
        'id'           => 'tgmpa',

**Comment by codiblog** [comment]
Following link help you to fix it in your latest version. I solved it in my own product

<a href="http://www.codiblog.com/2015/04/fixed-tgm-bulk-installer-missing.html">[Fixed] "TGM_Bulk_Installer" missing issue in wordpress version</a>

**Comment by jrfnl** [comment]
@Mina88 This is already fixed in the 2.4.2 release. Please point people to the latest release instead of to the raw develop code.
https://github.com/TGMPA/TGM-Plugin-Activation/releases/latest
