### ISSUE TITLE
HostGator doesn't seem to like TGMPA's methods

### ISSUE THREAD

**Issue by chrishoward-au** [thomasgriffin/TGM-Plugin-Activation#187]
Hi Thomas

HostGator is throwing up 403 Forbidden errors when people try to install my dependent plugins via TGMPA.

The dependent plugin is on Amazon S3.

Here's the message from HG, which would suggest that WP or TGMPA is writing to a folder it's not allowed to.

![hg-403](https://cloud.githubusercontent.com/assets/129821/2702947/41004e3a-c441-11e3-9336-de24aaabb177.jpg)

I have contacted HG as well.

**Comment by ale13jo** [comment]
Hi, if your theme includes the plugins zip file change the GET param plugin_source to relative path like ../wp-content/theme... It works for me.
