### ISSUE TITLE
Upgrading the package plugins

### ISSUE THREAD

**Issue by SyntaxThemes** [thomasgriffin/TGM-Plugin-Activation#192]
Hi Thomas

I am having a problem with the TGM plugin when I am trying to upgrade plugins which I have already installed using the TGM plugin.  When you change the version number in the configuration, the TGM plugin correctly displays that the plugin needs to be upgraded and displays "The following plugin needs to be updated to its latest version to ensure maximum compatibility with this theme".  The problem is the "Install Plugins" page is never re-activated and I do not get an option to update the plugin as shown in this video http://www.screenr.com/uYmH.  Is there a setting which I am missing apart from updating the version number?  Or do I have to re-named the packaged .zip file?  

At the moment the workaround is to deactivated the theme then uninstall the plugin.  Then, re-activate the theme and then the TGM plugin will install the new plugin.  This is not ideal as it does not display a maintenance mode and also it changes the theme on the front end.

This is an awesome solution overall and I must just be missing something.  I can see that the solution I am looking for is on this TGM plugin video url above.  But im wondering if you have changed the feature since this was made.

Thank you very much.

**Comment by KingYes** [comment]
+1

**Comment by mintbird** [comment]
+1 This is a *must have* feature.

**Comment by hatra-e** [comment]
I would also very much like to see this feature in a future version. 

TGM PA already notifies the user that there is an update available. It would be great if the user can then click a button to update the plugin. Or even better - use the new update functionality introduced in WP 4.2.  

This guy here got it working:

http://themeforest.net/forums/thread/theme-bundled-plugins-review-rules/173342

https://github.com/bitfade/pixelentity-theme-bundled-plugins/blob/master/class-pixelentity-theme-bundled-plugins.php

https://www.youtube.com/watch?v=kJAhC02xAHQ

**Comment by GaryJones** [comment]
@hatra-e Just needs someone to do us a pull request with their changes integrated into the `develop` branch and we'll take a look.

**Comment by nomansbeauty** [comment]
Heard that this author has this updates plugin feature in his version: https://github.com/duckzland/TGM-Plugin-Activation
But I am not sure..

**Comment by GaryJones** [comment]
We're handling this internally now, based on the work submitted by others.

**Comment by nomansbeauty** [comment]
Cool thanks :+1:  We all are anxiously waiting for the new version :) Thanks.

**Comment by jrfnl** [comment]
I'd like to invite everyone in this thread to test PR #381 / https://github.com/thomasgriffin/TGM-Plugin-Activation/tree/feature/192-add-updating-workflow which implements this.

Feedback very welcome. Please add your comments in the PR thread #381

**Comment by GaryJones** [comment]
This has now been merged into the `develop` branch. The feature branch has been deleted.
