### ISSUE TITLE
Fatal error: Class 'TGM_Bulk_Installer' not found

### ISSUE THREAD

**Issue by dimoncheg777** [thomasgriffin/TGM-Plugin-Activation#222]
Hello! That error happened when i select more than one plugin in list. Here is a full text:

Fatal error: Class 'TGM_Bulk_Installer' not found in mypath\www\wp-content\themes\mytheme\library\tgm-plugin-activation\class-tgm-plugin-activation.php on line 1579

How to fix that? Thank you for help!

**Comment by jrfnl** [comment]
A fix for this was already committed to the develop branch: https://github.com/thomasgriffin/TGM-Plugin-Activation/commit/1e98e425f4a3bc43bd0fa05fe74a4268aa624f33

**Comment by GaryJones** [comment]
Duplicate of #185.
