### ISSUE TITLE
Theme Check Issue ! [Resolved]

### ISSUE THREAD

**Issue by InsertCart** [thomasgriffin/TGM-Plugin-Activation#224]
We know that WordPress introduce in Theme Check latest plugin when i run scan it gives me error 

REQUIRED: screen_icon() found in the file class-tgm-plugin-activation.php. Deprecated since version 3.8.
Line 391: screen_icon( apply_filters( 'tgmpa_default_screen_icon', 'themes' ) );
Line 1585: screen_icon( apply_filters( 'tgmpa_default_screen_icon', 'themes' ) ); 

So any update on this issue
Here is plugin http://downloads.wordpress.org/plugin/theme-check.zip

**Comment by bfintal** [comment]
This should be closed now e61b32fc8b609d6a3711a55f6e54900d3ca03d59
