### ISSUE TITLE
force_deactivation = true plugins shouldnt show as recommend

### ISSUE THREAD

**Issue by unsalkorkmaz** [thomasgriffin/TGM-Plugin-Activation#225]
As title says, i tried to disable some plugins with 'force_deactivation'    => true, but now it shows plugin as recommended. And its only added to 'switch_theme', why not 'admin_init' ?

**Comment by jrfnl** [comment]
I believe you misunderstand the 'force-deactivation' parameter.

Force deactivation is meant for __*theme specific plugins*__ which are only needed while the theme is active. On switching away from the theme, the plugin will be force-deactivated.

Force deactivation is __*not*__ meant to deactivate (incompatible) plugins when the theme *becomes* active.

While the explanation of the feature can probably do with some improvement, the behaviour is correct.
