### ISSUE TITLE
Remove Plugins on theme deactivation

### ISSUE THREAD

**Issue by Tidal-Wave** [thomasgriffin/TGM-Plugin-Activation#233]
After much google, I think I know the answer, but I wanted to make sure. When using this to install theme specific plugins from file, is there a way to UNINSTALL the plugin on theme deactivation? Im left with plugins that don't behave as intended on other themes if I deactivate the theme. They get deactivated, but they still get listed in Plugins.

**Comment by GaryJones** [comment]
This is a tricky one. Let's take an example.

My theme supports CPTs, and like a good developer, I register these via a plugin which I include within the theme and set as required in TGMPA. That way, when the user changes their theme, they still have access to the content as the CPT is still registered. We can't just blanket uninstall plugins.

We could look at uninstalling optional plugins, or have a list of which ones potentially could be uninstalled, but that's still going to be a pain for users if they actually still wanted a plugin installed, or were just temporarily changing themes and a plugin doesn't maintain settings upon deactivation and reactivation.

**Comment by Tidal-Wave** [comment]
I get what your saying on the theme switching. At the time I was hoping for better control of a theme I made with 3rd party plugins installed. 

I concede for now but still think an option would be nice.

**Comment by GaryJones** [comment]
The other issue, would be if multiple products both used TGMPA and wanted plugin X to be active. Having your theme try and uninstall it when another plugin still needs it to be present and active, may cause issues.

**Comment by Tidal-Wave** [comment]
:+1:

**Comment by ljubacanoa** [comment]
Sorry, but I'm looking exactly to found the way how to accomplish uninstallation on theme deactivation and I can't agree with argument for lack of option:

1) Argument about depending plugin is wrong, as here is about the plugins bundled with theme (in other words, developer will take care about the listed plugins and its dependencies).   
2) That is only the option and should be set by default to false. So, it certainly will not affect nobody who don't need it.

So, please be kind and add the option (word say itself - option mean, optional usage).
