### ISSUE TITLE
Undefined index: skin_update_failed_error

### ISSUE THREAD

**Issue by parhumm** [thomasgriffin/TGM-Plugin-Activation#240]
I'm seeing this error when select all plugins install(all plugins not one by one):
```
Notice: Undefined index: skin_update_failed_error in class-tgm-plugin-activation.php on line 2110
```

**Comment by jrfnl** [comment]
This should be fixed by PR #260

**Comment by parhumm** [comment]
@jrfnl Sorry, what can I do now?

**Comment by jrfnl** [comment]
@parhumm Either apply the changes from #260 yourself or switch to the develop branch in which the changes have been merged.

**Comment by parhumm** [comment]
@jrfnl Thanks, it was solve my problem.
