### ISSUE TITLE
Install/Activate plugins without manual operations

### ISSUE THREAD

**Issue by gyopiazza** [thomasgriffin/TGM-Plugin-Activation#242]
I was wondering if it's currently possible (or planned) to install/activate plugins without user intervention. For example, instead of showing a message asking to install plugins, they could be automatically installed/activated showing a message to notify the user of what happened.

Thank you for the help and TGM Plugin Activation! :)

**Comment by KingYes** [comment]
+1
I'm need this too :)

**Comment by jrfnl** [comment]
-100
This would be a ***huge*** security issue. Any mal-intending plugin/theme author could pull in code from just about anywhere that way.

**Comment by thomasgriffin** [comment]
I agree with @jrfnl - this is why we did not include it in the first place. We do give the option to force activation, but the onus of installation will always be on the user, not on the provider.

**Comment by gyopiazza** [comment]
I'm not sure I understand your point. A mal-intending plugin or theme can already include any sort of malicious code without having to pull it from somewhere else.

It's true that a "clean" plugin/theme would pass security tests, so pulling the malicious code afterwards would trick it. But that is still possible without TGMPA. For example, a malicious PHP file hosted somewhere can be downloaded to the 'uploads' folder and let the offender do practically anything.

What I mean is that this issue is not related to TGMPA, but to webapps in general.

As a transversal solution, would it be easy enough to add a "Install all" link to the notification message? This way it's a step less for the end users (I'm especially thinking about premium themes customers).

Thanks! :)

**Comment by jrfnl** [comment]
@gyopiazza That it can be done does not mean that this plugin should facilitate it....

**Comment by gyopiazza** [comment]
@jrfnl I really don't think mal-intended people need TGMPA to make damages, but of course I respect your decision.

**Comment by gyopiazza** [comment]
I've read that a new version of the TGMPA is coming out, and really looking forward for the improvements! :)

In the meanwhile I've created a little solution to automatically install/activate plugins. The user intervention is still required, because they need to visit the TGMPA admin page (nothing happens in the background). I'll leave it here for anybody that might need it (and help test it).

It's a bit hackish but it works (I plan to refine it a little, maybe removing the JS part):
https://gist.github.com/gyopiazza/9d912ecfb6825dd981a7

The reason why I made it is that, for commercial products, having to ask the clients to install plugins before they can use a theme is not ideal.

I understand and respect your idea to install/activate plugins only after an explicit user action.

Ideally, from a usability point of view, that shouldn't be more than 1 click. For example in the notification box, there could be just 1 link saying "Install required plugins" and another "Go to the recommended plugins page". The "Install required plugins" should begin the installation/activation automatically.

About the security concerns, please excuse me but I'm still not convinced. A plugin named "Fancy slider" might be doing any kind of damages, but the user might install it anyways because it's required by the theme.

Thank you!
