### ISSUE TITLE
How do i use TGM Plugin Activation inside another plugin to pull in dependent plugins?

### ISSUE THREAD

**Issue by ghost** [thomasgriffin/TGM-Plugin-Activation#243]
Does this plugin work in a plugin?

I want to use the library but i want to use it for a plugin that is dependent on other plugins, specifically a recipe plugin that requires scribus posts 2 posts.

Is this possible and if so where do i put the example.php code ?

**Comment by greataussiepie** [comment]
thanks :+1:
