### ISSUE TITLE
Class 'TGM_Bulk_Installer' not found

### ISSUE THREAD

**Issue by EusebiuOprinoiu** [thomasgriffin/TGM-Plugin-Activation#268]
Hello, Thomas!
There seems to be a problem when trying to install multiple plugins in bulk.

Fatal error: Class 'TGM_Bulk_Installer' not found in <code>class-tgm-plugin-activation.php</code> on line 1576.

**Comment by CREEATION** [comment]
:+1: - same here but on line 1580 in `tgmpa.class.php`

**Comment by GaryJones** [comment]
Is this using the latest develop branch code, or master?

**Comment by EusebiuOprinoiu** [comment]
I use the latest code from the master branch.
I did a test with the one from development and the plugins were installed without a problem, but there are other issues like deprecated functions and warnings thrown by Theme Check.

**Comment by GaryJones** [comment]
Theme Check-related issues would be a separate issue(s), so since the `develop` branch worked for you, I'll mark this as closed. Thanks for reporting.

**Comment by GaryJones** [comment]
Duplicate of #185.

**Comment by marllon90** [comment]
Hi you need change the variable '**menu**', [**line 807**] to '**menu_title**'

`$keys = array( 'default_path', 'has_notices', 'dismissable', 'dismiss_msg', 'menu', 'is_automatic', 'message', 'strings' );`

`$keys = array( 'default_path', 'has_notices', 'dismissable', 'dismiss_msg', 'menu_title', 'is_automatic', 'message', 'strings' );`
