### ISSUE TITLE
Move "Install Plugins" from "Appearance"

### ISSUE THREAD

**Issue by echo1consulting** [thomasgriffin/TGM-Plugin-Activation#272]
Is there a way to move the "Install Plugins" submenu away from "Appearance"? I have TGM packaged in a plugin, and it does not make much sense for it to be there.

Thanks,

**Comment by jrfnl** [comment]
At this moment, it is difficult to do so, though you could use the develop branch and the code in PR #221 to make it happen.

FYI: work will start on v3 in the near future (probably March when I'm no longer traveling) and this is one of the things which is already on the roadmap for v3 - or rather: a set location for the submenu outside of appearance as depending on whether a user has a theme and/or plugins installed with TGMPA, the menu location could jump around now and we'd like to make it more predictable.

**Comment by strider72** [comment]
It seems something like this would make a lot more sense under Tools.
Hmm... if it's talking about requirements for the site, perhaps even a submenu under Dashboard might be more appropriate?

**Comment by expres-web** [comment]
Any progress? Also, I welcome this opportunity :)

**Comment by GaryJones** [comment]
This is now possible in the `develop` branch.

**Comment by expres-web** [comment]
I tried it and I rewrote themes.php on plugins.php and edit_theme_options on edit_plugins_options and I'm on page wp-admin/plugins.php?page=tgmpa-install-plugins but writes me that "You do not have sufficient permissions to access this page."

thx

**Comment by GaryJones** [comment]
There is no capability called `edit_plugins_options`: https://codex.wordpress.org/Roles_and_Capabilities

**Comment by expres-web** [comment]
To me it did not work :( I do not know what there I give everything to me previewed below plugins :(
