### ISSUE TITLE
Automatic plugin activation and installation

### ISSUE THREAD

**Issue by AlexandruDoda** [thomasgriffin/TGM-Plugin-Activation#279]
Hey,

I am wondering if there is any way to run the plugin installer / activator automatically after activating the theme. I would like to make some plugins install and activate automatically if they are not installed / activated without having the notice and all the extra steps. Any suggestions? Thanks!

Alexandru Doda

**Comment by shivapoudel** [comment]
:+1: IMO xD

**Comment by GaryJones** [comment]
We've discussed this previously, and for now, this won't happen. 

I could create a theme that bundles all manner of plugins which if automatically installed and activated could scrape your system and send me passwords and so on. 

By requiring the human interaction, we give the final choice to users to activate those plugins (or just dismiss the admin notice).

**Comment by AlexandruDoda** [comment]
I see, okay :) The reason I wanted this is because I am developing a framework which makes use of ACF for some core functionality and wanted to make sure the plugin is always installed. Good point with the human interaction.
