### ISSUE TITLE
Name of plugin from GitHub 

### ISSUE THREAD

**Issue by danfisher85** [thomasgriffin/TGM-Plugin-Activation#283]
Hi,

I'm installing plugin from GitHub with TGM. After installation it adds '_master' word to plugin name, e.g. 'plugin-name_master'.
Is there any option to remove this extra word 'master'?

Thanks!

**Comment by GaryJones** [comment]
That's the name of the zip that comes from GitHub. We should be able to check the URL and amend the install folder, or at least provide a hook / instructions on how you could add it to your theme / plugin.

**Comment by jrfnl** [comment]
This should be fixed by PR #327
