### ISSUE TITLE
add_query_arg fix breaks plugin installation functionality

### ISSUE THREAD

**Issue by dennyf** [thomasgriffin/TGM-Plugin-Activation#292]
Hi,

After the `add_query_arg()` fix has been applied in this commit:
fd8e0942e3e916dbd5232ea39bb17670f500ed6c
the plugin installation functionality doesn't work anymore.

When I click on the Install button, I'm redirected to the URL with the following format:
http://example.com/wp-admin/themes.php?page=install-required-plugins&_wpnonce=xxxxxxxxxx#038;plugin=example-plugin&plugin_name=ExamplePlugin&plugin_source=repo&tgmpa-install=install-plugin
I believe that the issue's caused by the escaped **&** character in the URL: `#038;`

**Comment by shivapoudel** [comment]
Strictly we should use utilize `esc_url_raw()` instead `esc_url()` for `add_query_args()` and this will get fix ;)

**Comment by themeblvd** [comment]
I've noticed this same problem, too. Just to be clear, the issue is when you click "Install" for and individual plugin.

**Comment by themeblvd** [comment]
In this case, I believe you don't need to use `esc_url()` at all because when you call `add_query_arg()`, you're feeding in the `$url` param like:

    add_query_arg( array(...), network_admin_url('plugin-install.php') );

The vulnerability only exists if the `$url` parameter is not passed into `add_query_arg()`.

https://make.wordpress.org/plugins/2015/04/20/fixing-add_query_arg-and-remove_query_arg-usage/

**Comment by NateWr** [comment]
I believe there is only one place where `esc_url()` is required and that's [this one](https://github.com/thomasgriffin/TGM-Plugin-Activation/blob/master/class-tgm-plugin-activation.php#L738). All the other places uses a safe url, like one generated by `admin_url()`.

**Comment by shivapoudel** [comment]
@GaryJones Can you fix this as soon as possible ;)

**Comment by jrfnl** [comment]
Would be great if any of you could test this PR to make sure it fixes the issue:
https://github.com/thomasgriffin/TGM-Plugin-Activation/pull/294

**Comment by Stephen-Cronin** [comment]
Not sure you need all of those changes in #294. For example, to quote Gary Pendergast:

"You don’t need to escape the `$url` being passed to `request_filesystem_credentials()` at all - `request_filesystem_credentials()` does that for you"

I *think* the changes in #293 will suffice - though I certainly could be wrong on this.

Also, we really need to get the version number bumped so we can tell which version is fixed.

**Comment by NateWr** [comment]
I'm going to leave version bumping to @thomasgriffin unless he wants it done as part of the PR.

**Comment by GaryJones** [comment]
> The vulnerability only exists if the $url parameter is not passed into add_query_arg().

Doesn't matter. If `network_admin_url()` is like `admin_url()` in that the result is filterable, it's possible (although unlikely) that a filter could be adding in scripting. Escaping always is the best approach.

**Comment by GaryJones** [comment]
Please give the 2.4.1 branch a try.
