### ISSUE TITLE
Bulk installation error "http://repo" in hotfix/2.4.1

### ISSUE THREAD

**Issue by themeblvd** [thomasgriffin/TGM-Plugin-Activation#298]
When using the hotfix/2.4.1 branch, if you're using plugins from wordpress repo, there is an error with bulk installation.
 
![screen shot 2015-04-21 at 11 18 02 am](https://cloud.githubusercontent.com/assets/1952287/7260692/5749dcdc-e818-11e4-941f-a9d08f2c246b.png)

I believe this is happening because of how you're using `esc_url()` here:

https://github.com/thomasgriffin/TGM-Plugin-Activation/blob/hotfix/2.4.1/class-tgm-plugin-activation.php#L1351

If I'm understanding right, TGM puts the URL in that form's checkbox as "repo", and this is how you're identifying that you need to build the URL to the plugin from the WP repo. 

However, when you call `esc_url( $item['url'] )`, you're changing `$item['url']` from "repo" to "http://repo" -- Then when the form passes the the data to the bulk installer, it doesn't have that "repo" value any more, and doesn't know to build the URL to the plugin at wordpress.org.

**Comment by Webcreations907** [comment]
Seems that changing that function to something like below may work right for bulk install/activate.

```
public function column_cb( $item ) {
            $plugin_url = ( $item['url'] == 'repo' ) ? 'repo' : esc_url( $item['url'] );
            $value = $item['file_path'] . ',' . $plugin_url . ',' . $item['sanitized_plugin'];
            return sprintf( '<input type="checkbox" name="%1$s[]" value="%2$s" id="%3$s" />', esc_attr( $this->_args['singular'] ), esc_attr( $value ), esc_attr( $item['sanitized_plugin'] ) );

        }
```

**Comment by GaryJones** [comment]
Thanks for testing and reporting - I'll take a look. :+1:

**Comment by GaryJones** [comment]
I couldn't replicate your screen shot, but I like the fix anyway.

Please `git fetch` and `git merge origin hotfix/2.4.1` to try the latest version of the branch to see if that fixes it for you @themeblvd.

**Comment by themeblvd** [comment]
Thanks!
