### ISSUE TITLE
Release new, updated version for packagist?

### ISSUE THREAD

**Issue by AaronHolbrook** [thomasgriffin/TGM-Plugin-Activation#299]
Last release is from August of last year, any chance you could release an updated stable version with the recent fixes?

**Comment by GaryJones** [comment]
I need to get @thomasgriffin to enable auto-updating of packagist, but then yes, for each new tagged release, packagist will update.

The plan is to have 2.4.1 done in the next day or two, and then 2.5.0 with all of the other recent changes done _soon_.

**Comment by jimmyandrade** [comment]
Any chance you guys could release an updated stable version on packagist with the changes of 2.4.2?

**Comment by GaryJones** [comment]
Thanks for the reminder. I've forced an update and something updated - please let me know if all is well.

https://packagist.org/packages/tgm/plugin-activation

**Comment by AaronHolbrook** [comment]
Looks good thanks @GaryJones

**Comment by jimmyandrade** [comment]
Thanks, @GaryJones, it's working :+1:

**Comment by GaryJones** [comment]
Folks,

Going forwards, the composer package is named per the new organisation: https://packagist.org/packages/tgmpa/tgm-plugin-activation .

The [old package](https://packagist.org/packages/tgm/plugin-activation) has been marked as abandoned and recommends the new package.

**Comment by jimmyandrade** [comment]
@GaryJones, Great! I was really missing it.

**Comment by GaryJones** [comment]
It also makes it easy to find us now, both with `composer search tgmpa`, and on Packagist website :-)
