### ISSUE TITLE
Undefined property: TGM_Bulk_Installer_Skin::$admin_page_base

### ISSUE THREAD

**Issue by pyrchlmarcin** [thomasgriffin/TGM-Plugin-Activation#301]
Hi,

I'm using latest version of TGM-Plugin-Activation 2.4.1 and WP 4.1.2 and while trying to make a bulk install I'm getting this error/notice at the end of bulk install ( after all plugins were installed ):

Notice: Undefined property: TGM_Bulk_Installer_Skin::$admin_page_base in C:\wamp\www\wordpress\wp-content\themes\division\admin\class-tgm-plugin-activation.php on line 2257
Call Stack
#	Time	Memory	Function	Location
1	0.0100	398096	{main}( )	..\themes.php:0
2	0.0100	465680	require_once( 'C:\wamp\www\wordpress\wp-admin\admin.php' )	..\themes.php:10
3	6.7664	44339736	do_action( )	..\admin.php:212
4	6.7664	44341264	call_user_func_array:{C:\wamp\www\wordpress\wp-includes\plugin.php:496} ( )	..\plugin.php:496
5	6.7664	44341464	TGM_Plugin_Activation->install_plugins_page( )	..\plugin.php:496
6	6.7674	44346272	TGMPA_List_Table->process_bulk_actions( )	..\class-tgm-plugin-activation.php:428
7	10.5446	44846592	TGM_Bulk_Installer->bulk_install( )	..\class-tgm-plugin-activation.php:1691
8	15.6409	44727992	TGM_Bulk_Installer_Skin->bulk_footer( )	..\class-tgm-plugin-activation.php:1897

there is no such property as $admin_page_base in class TGM_Bulk_Installer_Skin nor in any base classes which are being extended and the link at the very bottom of page which says:

Return to Required Plugins Installer

is broken becuase it link to this:

http://localhost/wordpress/wp-admin/?page=install-required-plugins

instead of this:

http://localhost/wordpress/wp-admin/themes.php?page=install-required-plugins

BR

**Comment by Webcreations907** [comment]
Was just creating a PR for this, maybe it will help you out :smile:

**Comment by GaryJones** [comment]
Just a note: this is the develop branch, not the 2.4.1 release.
