### ISSUE TITLE
Latest release - errors in text editor

### ISSUE THREAD

**Issue by shilpapatil** [thomasgriffin/TGM-Plugin-Activation#303]
Hi,

TGM-Plugin-Activation v 2.4.1
class-tgm-plugin-activation.php showing errors in code editor. 
Please check if these are fine.
![screenshot-1](https://cloud.githubusercontent.com/assets/4683255/7272213/e231d02c-e906-11e4-9597-20f9dca6eeff.jpg)
![screenshot-2](https://cloud.githubusercontent.com/assets/4683255/7272214/e232adb2-e906-11e4-8ad7-43cd601f4f90.jpg)

**Comment by GaryJones** [comment]
Any clue what it is complaining about?

**Comment by shilpapatil** [comment]
As per code hinting, these are syntax error.
On code lines with -
- global object $GLOBALS['tgmpa']::$instance
- urlencode() in array

**Comment by jrfnl** [comment]
@shilpapatil No syntax errors there, probably syntax parser errors in the editor though.

**Comment by Jelena1** [comment]
This is what I get when try to install theme: 
Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in /home/.../class-tgm-plugin-activation.php on line 1140

**Comment by shilpapatil** [comment]
This is what I got in editor:
![screenshot-3](https://cloud.githubusercontent.com/assets/4683255/7274991/e1bc754e-e91e-11e4-9744-edd2ec261e25.jpg)

**Comment by AndonDesign** [comment]
the parse error "Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM ..." referencing <code>$GLOBALS['tgmpa']::$instance</code> might be related to a version of PHP lower than PHP 3.5, I encountered similar error on PHP 5.2.17, I believe the lowest WP currently supports is PHP 5.2.4 (https://wordpress.org/about/requirements/)

**Comment by goodwinpress** [comment]
I have this problem too - T_PAAMAYIM_NEKUDOTAYIM in /home/.../class-tgm-plugin-activation.php on line 1140
PHP version is 5.2.17

**Comment by Jelena1** [comment]
it's 5.3 PHP version

**Comment by shilpapatil** [comment]
PHP 5.5.12

**Comment by jrfnl** [comment]
Duh.. of course... I can see the issue with PHP 5.2 and am currently working on a solution.

@shilpapatil are you sure you're running into this with PHP 5.5 ??? I've just ran lints on the file with both PHP 5.5.9 as well as 5.5.12 and passes with flying colours.

**Comment by jrfnl** [comment]
Ok, I send in PR #306 which should fix this. Testing appreciated.

**Comment by AndonDesign** [comment]
thanks for the effort I just tested it on localhost PHP 5.4.16 and got this error:
<code>Fatal error: Call to undefined function get_instance() in .../class-tgm-plugin-activation.php on line 1138</code>
I hope this helps

**Comment by goodwinpress** [comment]
Thanks for improving, but there is the same error - get_instance() at 1138 (5.2.17)

**Comment by jrfnl** [comment]
Yeah, sorry about that. I seem to have had my head elsewhere. All fixed now with my latest commit.

**Comment by shilpapatil** [comment]
@jrfnl pardon my ignorance. My editor supports PHP 5.4
Seems like you can ignore my original post, as it is only me who getting those syntax errors :)

**Comment by shivapoudel** [comment]
@jrfnl can you link the commit?

**Comment by AndonDesign** [comment]
Error's gone (thanks) BUT now the link is gone from the menu and there are no notices if I use your latest fix from #306

**Comment by jrfnl** [comment]
@AndonDesign Yup, I noticed that too, working on it.

**Comment by jrfnl** [comment]
Ok, fixed it - working fix in PR #309 which will probably be merged into develop soon. Testing still appreciated.

**Comment by goodwinpress** [comment]
Thank you!!!

**Comment by AndonDesign** [comment]
Not sure if related to latest commit (https://github.com/thomasgriffin/TGM-Plugin-Activation/commit/030bdcc8c8a42c1ab0c79d3661ee764d18a8d5f5) but now I'm getting the following error when attempting bulk install: <code>Fatal error: Call to undefined method WP_Upgrader::construct() in .../class-tgm-plugin-activation.php on line 1859</code>

**Comment by jrfnl** [comment]
@AndonDesign Thanks for paying attention, I obviously am not, keep making typos today ;-) PR #311 fixes this.

**Comment by AndonDesign** [comment]
works a treat now! thanks

**Comment by shilpapatil** [comment]
Thanks.
