### ISSUE TITLE
Bulk installer throwing fatal error in 2.4.1

### ISSUE THREAD

**Issue by kievins** [thomasgriffin/TGM-Plugin-Activation#312]
Hey,

The bulk installer (installing a bundled plugin file) keeps throwing this error after updating to 2.4.1 from 2.4.0. I'm using WP 4.1.2 and PHP 5.4.17. 

Fatal error: Call to undefined method WP_Upgrader::construct() in /home/planetshine/webapps/htdocs/test/callisto/wp-content/themes/callisto/core/lib/tgmPluginActivation.class.php on line 1859

Let me know if you need more info etc.

**Comment by jrfnl** [comment]
Fixed by PR #311
