### ISSUE TITLE
Fatal error: Call to undefined method WP_Upgrader

### ISSUE THREAD

**Issue by Jelena1** [thomasgriffin/TGM-Plugin-Activation#313]
I downloaded latest version (updated 5 hours ago in the moment of writing) and got this error when try to install plugins:

Fatal error: Call to undefined method WP_Upgrader::construct() in /home/.../class-tgm-plugin-activation.php on line 1883

Is there a fix for this or is this a new bug? Please paste a link if fix exists, thanks.

**Comment by jrfnl** [comment]
@Jelena1 This should be fixed by the PR which was just merged by @GaryJones . If you download again, all should be fine.
