### ISSUE TITLE
Please add plugin updating

### ISSUE THREAD

**Issue by fgsfdgsdfgsd** [thomasgriffin/TGM-Plugin-Activation#318]
Here you have several lines of code that needs to be added for plugin to have an option to update plugins from theme files.

http://themeforest.net/forums/thread/modified-tgm-plugin-added-option-to-update-the-plugins/105830
http://pastebin.com/0jh83Xmw
http://pastebin.com/5BLEASpd

It is just a small fix and it makes a lot easier for users to update plugins that are bundled with theme.

A lot of themeforest authors are using this modified script.

Thank you!

**Comment by zaferyardimci** [comment]
+1

I wating for that..

**Comment by jrfnl** [comment]
Closing as duplicate of #197. Feel free to send in a pull request with the changes you'd like to see.

**Comment by jrfnl** [comment]
I'd like to invite everyone in this thread to test PR #381 / https://github.com/thomasgriffin/TGM-Plugin-Activation/tree/feature/192-add-updating-workflow which implements this.

Feedback very welcome. Please add your comments in the PR thread #381
