### ISSUE TITLE
2.4.1 Bulk  Installation bug

### ISSUE THREAD

**Issue by DKudleichuk** [thomasgriffin/TGM-Plugin-Activation#328]
Hello

Just want to report an issue, i've got this error http://i.cubeupload.com/GjnchN.png

PHP 5.3.27 (i'm using OpenServer)
WordPress 4.2

**Comment by jrfnl** [comment]
Closing as duplicate of #185 which has been solved for a long while in `develop`. 2.4.1 is only a security release on the existing 2.4.0. It doesn't fix anything else.

**Comment by DKudleichuk** [comment]
Sorry but how it can be fixed a long time ago if i'm still getting this error? The only version that works for me is 2.3.6, do you have some example how should i use TGM to leave this with the latest version 2.4.1?

**Comment by GaryJones** [comment]
Because we've not made a feature or non-security fix release since March 2014. 

The aim is to release 2.5.0, which contains this fix, in the next couple of weeks.

**Comment by DKudleichuk** [comment]
Thank you for your fast answer. Waiting for 2.5.0 :)
