### ISSUE TITLE
Fatal error: Call to protected method TGM_Plugin_Activation::_get_plugin_data_from_name() from context 'TGMPA_List_Table' in class-tgm-plugin-activation.php on line 1426

### ISSUE THREAD

**Issue by ryanlabelle** [thomasgriffin/TGM-Plugin-Activation#334]
I just updated to 2.4.1 for the XSS fix and got this error, any thing I might be doing wrong?

Thanks for an awesome plugin!

**Comment by jrfnl** [comment]
@ryanlabelle I believe you must have updated to the develop branch not to the 2.4.1 release as that error only just got merged and I already submitted a fix #333 which I expect will be merged soon.

You can find the 2.4.1 release here: https://github.com/thomasgriffin/TGM-Plugin-Activation/releases/tag/2.4.1

Closing as duplicate.

**Comment by ryanlabelle** [comment]
Thank you and sorry for that. All better now.
