### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Goldenworks** [thomasgriffin/TGM-Plugin-Activation#336]
Hello there,

After updating the plugin files from 2.4.0 to 2.4.1, when trying to install any plugin(local or repository - for example wp-pagenavi) from Appearance -> Install Plugins I receive this error:

Fatal error: Call to protected method TGM_Plugin_Activation::_get_plugin_data_from_name() from context 'TGMPA_List_Table' in C:\Server\Apache2\htdocs\wordpress_ht\wp-content\themes\hubtechnologies\framework\class-tgm-plugin-activation.php on line 1427

**Comment by shivapoudel** [comment]
Ref: #333 and #334

**Comment by jrfnl** [comment]
Closing as duplicate. P.s.: you're not using version 2.4.1.

**Comment by Goldenworks** [comment]
Ooops yes you are right, I fixed it now, sorry for trouble...

**Comment by GaryJones** [comment]
> P.s.: you're not using version 2.4.1.

I've not committed yet, but I'll be changing the readme and version numbers in `develop` to `2.5.0-alpha` to avoid this confusion.
