### ISSUE TITLE
Install link shows when "installed but not activated"

### ISSUE THREAD

**Issue by ryanlabelle** [thomasgriffin/TGM-Plugin-Activation#342]
http://new.tinygrab.com/6407caa59e8dc07b6056ba0d570f31948552d58652.png

I'm using 2.5.0-alpha

**Comment by GaryJones** [comment]
Thanks for reporting.

Does that happen for all WPORG repo plugins? Does it happen for Bundled plugins?

**Comment by jrfnl** [comment]
@GaryJones I just tested - happens for all. Are you looking into this or want me to have a look ?

**Comment by ryanlabelle** [comment]
Thanks for looking into this and patching for the latest WP XSS.

**Comment by jrfnl** [comment]
Never mind - found it. See PR $344
