### ISSUE TITLE
Fatal error: Call to undefined function TGM_Bulk_Installer_Skin() in class-tgm-plugin-activation.php on line 1784

### ISSUE THREAD

**Issue by atikrahman146** [thomasgriffin/TGM-Plugin-Activation#347]
Selecting list of all plugins and give command to install shows this error. I've downloaded new file just now.

Fatal error: Call to undefined function TGM_Bulk_Installer_Skin() in C:\xampp\htdocs\bio\wp-content\themes\salem\inc\class-tgm-plugin-activation.php on line 1784

**Comment by jrfnl** [comment]
Closing as duplicate of already solved issue #185.
