### ISSUE TITLE
Fatal error: Call to undefined function TGM_Bulk_Installer_Skin() 

### ISSUE THREAD

**Issue by Jelena1** [thomasgriffin/TGM-Plugin-Activation#352]
Version 2.5.0 - alpha, updated 21 hours ago in the moment of writing, gives following error on bulk install:

Fatal error: Call to undefined function TGM_Bulk_Installer_Skin() in /.../class-tgm-plugin-activation.php on line 1784

PHP version 5.3

**Comment by jrfnl** [comment]
Thanks for reporting - I'll send in a fix in a little while.

In the mean time, you can fix this locally by changing line 1784:
```php
$installer = new TGM_Bulk_Installer( TGM_Bulk_Installer_Skin( compact( 'url', 'nonce', 'names' ) ) );
```

to:
```php
$installer = new TGM_Bulk_Installer( new TGM_Bulk_Installer_Skin( compact( 'url', 'nonce', 'names' ) ) );
```
