### ISSUE TITLE
Question: $_GET['from'] ?

### ISSUE THREAD

**Issue by jrfnl** [thomasgriffin/TGM-Plugin-Activation#354]
I encountered the below bit of code, but can't seem to find any other reference in the code base to the 'from' variable. By the looks of it, the code has been in the repo from the second commit.

Anyone any idea what this is about ?

Ref: https://github.com/thomasgriffin/TGM-Plugin-Activation/blob/develop/class-tgm-plugin-activation.php#L544-L546
```php
if ( isset( $_GET['from'] ) ) {
	$url .= add_query_arg( 'from', urlencode( stripslashes( $_GET['from'] ) ), $url );
}
```

**Comment by GaryJones** [comment]
I can only assume it was meant to track where the plugin was coming from (source), but I can't see that it was used anywhere.

We don't appear to use it now, so delete the instance.
