### ISSUE TITLE
WooCommerce error during activation all plugins

### ISSUE THREAD

**Issue by dedalx** [thomasgriffin/TGM-Plugin-Activation#369]
If WooCommerce plugin included for activation you will get this error at the bottom after activation all plugins:

    Fatal error: Call to undefined function wc_get_screen_ids() in /Volumes/Storage/Dropbox/MAMP/htdocs/wp-test/wp-content/plugins/woocommerce/includes/admin/class-wc-admin.php on line 151

![Screenshot](http://take.ms/NAHc5)

**Comment by shivapoudel** [comment]
@dedalx can you show me the href link. Related to WooCommerce footer rating text conflict!

**Comment by dedalx** [comment]
Url is: /wp-admin/themes.php?page=install-required-plugins

**Comment by dedalx** [comment]
This issue was here in old TGM-Plugin-Activation and WP versions too (for example in WP 4.x and TGM version from month ago).

**Comment by shivapoudel** [comment]
Which version of WooCommerce is that. I am not getting any error buddy?

**Comment by dedalx** [comment]
WP 4.2.1, WooCommerce 2.3.8 

WP Debug is enabled:

define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', true);

**Comment by shivapoudel** [comment]
Definitely I have enabled `WP_DEBUG` xD

**Comment by dedalx** [comment]
So do you see this error now or not?

**Comment by shivapoudel** [comment]
@dedalx Yeah, and this is WooCommerce error.
I'm fixing this right now and submiting the pull to WC repo and will be available on next WooCommerce Update xD

**Comment by jrfnl** [comment]
@shivapoudel Thanks for figuring this one out.
@dedalx as the error is not ours, are you ok with me closing the issue ?

**Comment by shivapoudel** [comment]
@jrfnl this issue can be closed ;)

**Comment by dedalx** [comment]
Yes, close it

**Comment by shivapoudel** [comment]
@dedalx  Bug fixed - https://github.com/woothemes/woocommerce/commit/c0a8e4d87ea4fb244835faaf832089e5337bc9ef
