### ISSUE TITLE
I get “Fatal error: Class ‘TGM_Bulk_Installer’ not found

### ISSUE THREAD

**Issue by Theme20** [thomasgriffin/TGM-Plugin-Activation#377]
Hello, 

I get “Fatal error: Class ‘TGM_Bulk_Installer’ not found in /wp-content/themes/.../class-tgm-plugin-activation.php on line 1690”

How should i fix it.

**Comment by jrfnl** [comment]
By the sounds of it you are using an old version of TGMPA in your theme. Please update to the most recent version - https://github.com/thomasgriffin/TGM-Plugin-Activation/releases/latest

If this doesn't solve your problem, report back in this thread and I'll re-open.
