### ISSUE TITLE
Popup issue: There is no popup when plugin name is clicked.

### ISSUE THREAD

**Issue by ernilambar** [thomasgriffin/TGM-Plugin-Activation#597]
In plugin listing, when Plugin name is clicked, popup is supposed to be opened. But whole page is covered by the content rather than thickbox popup.
TGM: 2.6.1
WP: 4.5.2
OS: Ubuntu 14.04
Browser: Chrome Version 50.0.2661.102 (64-bit) / Firefox 46.0.1

I tested with Travel Eye theme ( https://wordpress.org/themes/travel-eye/ ). But it seems that this is not theme issue.

**Comment by jrfnl** [comment]
Hi @ernilambar Thanks for reporting. Unfortunately I cannot reproduce the issue. I've just tested in both Chrome as well as Palemoon on Windows and though it takes a few seconds to load, it all seems to work fine for me. Any particular plugin this happens with or does this happen for all plugins ?

**Comment by ernilambar** [comment]
I have this staging WP setup. You can check it here. http://review.thisistap.com/wp-admin/
Username : supervisor
Password: *************

PS: Please remove password from this comment after you copy it :D

**Comment by jrfnl** [comment]
Tested and I see what you mean. All the same I've tested in the same browsers as before where in my own test setup with the same WP version and TGMPA version, this didn't happen.

So... I'm wondering if another plugin or theme might be interfering ?

(As you mention it's a staging setup, I don't want to mess things up for you by switching theme, but I'd be interested to see what would happen if you'd switch to one of the TwentySomething themes).

**Comment by ernilambar** [comment]
@jrfnl You can change anything you want in there. I use that setup to review themes. :-)

**Comment by jrfnl** [comment]
@ernilambar I installed a small test plugin which loads a tgmpa config so that I could test independently of theme. Tested with the two other themes and all was fine. Tested again with the original theme and I can no longer reproduce the issue.
Not sure what's going on, but I do suspect it was to do with the theme and not TGMPA.

**Comment by ernilambar** [comment]
@jrfnl Thanks for testing. I have seen such problem in other themes also. So I doubt that it is only theme issue :) . I have added another theme Illdy which also use TGM 2.6.1. Facing same problem. 

But strange thing I noticed is that, this error occurs only if I dismiss admin notice by `Dismiss this notice`. If admin notice is not touched, it works as expected.

**Comment by ernilambar** [comment]
Closing as this is not replicable now.
