### ISSUE TITLE
Text domain doesn't update instances of tgmpa in download bundle

### ISSUE THREAD

**Issue by martinburdon** [thomasgriffin/TGM-Plugin-Activation#600]
When setting a text domain for a custom download of TGMPA the text domain inside the bundled file remains as 'tgmpa'.

**Comment by GaryJones** [comment]
Did you have the generator set to Theme, Child Theme or Plugin?

If applicable, did you have WordPress.org, Theme Forest, or Other as the distribution platform?

**Comment by martinburdon** [comment]
Hi Gary, I had it set to Theme and ThemeForest.

**Comment by jrfnl** [comment]
Hi @martinburdon, when we created the Generator this was discussed with a representative of ThemeForest and they indicated that the text-domain did not need to be changed for themes hosted on ThemeForest.
The advantage of keeping the TGMPA text-domain is that your translators won't need to translate the TGMPA text strings and that you already have translations available for the TGMPA text strings in 17 languages (as of v 2.6.0),

For full details of the differences between the output based on the choices you can make in the form: https://github.com/TGMPA/TGM-Plugin-Activation/pull/519

**Comment by martinburdon** [comment]
Thanks for your response @jrfnl very informative :)

I'm sure I had a soft rejection before my theme got approved, asking me to keep all text domains within the theme to my themes slug, including TGMPA :/
I might push up an update to my theme reverting the text domain back to 'tgmpa' and see if it gets passed review.

Thanks for your time 👍

**Comment by jrfnl** [comment]
@martinburdon If the reviewers would comment on it, point them to @Stephen-Cronin who will put them right.

**Comment by martinburdon** [comment]
@jrfnl awesome stuff, thanks for the info :)

**Comment by Stephen-Cronin** [comment]
@martinburdon - Yep that should be fine. If you were to be soft rejected again for that reason, then when you're resubmitting, just add a note for the reviewer to check with me. Thanks!
