### ISSUE TITLE
add_theme_page() required on line 731

### ISSUE THREAD

**Issue by flovro** [thomasgriffin/TGM-Plugin-Activation#602]
Hello, 
I'm using the latest TGMPA Version and on theme check appearing the next issue:

REQUIRED: wp-content/themes/theme-name/inc/plugin/class-tgm-plugin-activation.php. Themes should use add_theme_page() for adding admin pages.

Line 731: $this->page_hook = call_user_func( '**add_submenu_page**', $args['parent_slug'], $args['page_title'], $args['menu_t

What shall I do?
Thanks,

**Comment by jrfnl** [comment]
Hope the fact that you closed the issue means you found the [Custom TGMPA Generator](http://tgmpluginactivation.com/download/)... ? That will auto-fix this for you if you select "publication on wordpress.org".

**Comment by heshaShawky** [comment]
I have used the generator for both wordpress.org and ThemeForest and the same problem every time 

Line 731: $this->page_hook = call_user_func( 'add_submenu_page', $args['parent_slug'], $args['page_title'], $args['menu_t

I hope there a solution?

Regards.

**Comment by heshaShawky** [comment]
I found the problem it's the generator doesn't work with chrome and IDM so I just re-download the files again using edge browser and no error's

**Comment by GaryJones** [comment]
IDM?

**Comment by heshaShawky** [comment]
( Internet download manager ) even the site pop up an ajax error I didn't notice it at the beginning! 

the error: 
Failed to retrieve TGMPA: Error: Ajax error for ../releases/TGM-Plugin-Activation-2.6.1.zip : 204 Intercepted by the IDM Advanced Integration

**Comment by noralam** [comment]
How can I download TGM without IDM?

**Comment by jrfnl** [comment]
@noralam http://tgmpluginactivation.com/download/
