### ISSUE TITLE
Plugin activation notice gets wrong-positioned (Unyson)

### ISSUE THREAD

**Issue by cojocaru3** [thomasgriffin/TGM-Plugin-Activation#604]
I'm new to TGMPA, and i'm having an issue:
After activating the theme, required plugins poup gets positioned wrong ( http://i.imgur.com/TA529tU.png ), how can i fix it ?

**Comment by jrfnl** [comment]
Which versions of TGMPA are you using with which version of WordPress ?

This was fixed in PR #509 which is included in the recent 2.6.0 and 2.6.1 releases.

**Comment by cojocaru3** [comment]
Shame on me, I was using an outaded version of TGMPA.

**Comment by jrfnl** [comment]
Happens to the best of us ;-)
