### ISSUE TITLE
Logic for Plugin X Lite OR Plugin X Premium

### ISSUE THREAD

**Issue by prionkor** [thomasgriffin/TGM-Plugin-Activation#619]
How should we handle this kind of special case where we recommend _Plugin X lite_ ( which is free ). Now if user have the _Plugin X Premium_ which is an extended version of _Plugin X lite_. Those two plugins can not be activated together and can create conflict if both activated.

This is one of the common cases now a days as many of developers have lite and premium version of a particular plugin.

Let me know your thoughts.

**Comment by jrfnl** [comment]
I'd recommend looking for a common function/method which is contained in both the Lite as well as the Premium version of the plugin and setting the `is_callable` configuration option for the plugin.
If the function/method is found, the plugin will be regarded as active, independently of whether the Lite or the Premium version is installed.

For more information, see the detailed configuration information: http://tgmpluginactivation.com/configuration/#h-plugin-parameters

Does that answer your question ?

**Comment by prionkor** [comment]
Yes, `is_callable` seems to be right choice! :)
