### ISSUE TITLE
Text domain is not being changed

### ISSUE THREAD

**Issue by milutinjaric** [thomasgriffin/TGM-Plugin-Activation#624]
http://prntscr.com/ceu63y
http://prntscr.com/ceu6p0

**Comment by jrfnl** [comment]
@DJMIMi That's correct. You've choosen Themeforest as your distribution channel and TF does not require you to change the text-domain. This has been discussed and approved by a representative of TF when the Custom Generator was created.

For detailed information on the different versions - see the table in the original PR: https://github.com/TGMPA/TGM-Plugin-Activation/pull/519 . The thread also contains the discussion showing that TF does not require the text-domain change.

If you - even though it's not needed - would still like to generate a version with an adjusted text-domain, just select "WordPress.org" as your distribution channel.

**Comment by milutinjaric** [comment]
Hi jrfnl.

They change rules all the time, everybody now get soft reject if multiple domains are used in theme :( since ThemeCheck plugin informs an error about it.

Regards

**Comment by jrfnl** [comment]
@DJMIMi The rules have not changed regarding this. TGMPA is allowed to have it's own text-domain on TF. This has been confirmed numerous times already. This is not a TGMPA issue, but an issue with theme reviewer education within ThemeForest.

If you get soft-rejected because of the text-domain, point the reviewer to the PR I mentioned above and/or ping @Stephen-Cronin when you resubmit - see: https://github.com/TGMPA/TGM-Plugin-Activation/issues/600#issuecomment-223163192

**Comment by milutinjaric** [comment]
Hi jrfnl.

Yes but in the reality every reviewer soft reject it which means another 2 or 3 days waiting and another if he insists on already 70+ which is current time wait for the first review and you see the issue.

I do not see that much hassle to add domain change for TF too to speed up process but again you decide ;)

Thanks for the great plugin.

Regards.

**Comment by jrfnl** [comment]
@DJMIMi

> Yes but in the reality every reviewer soft reject it which means another 2 or 3 days waiting and another if he insists on already 70+ which is current time wait for the first review and you see the issue.

I understand that that is inconvenient and a pain, but that again is really a TF internal issue and not something related to TGMPA.

> I do not see that much hassle to add domain change for TF too

There is no problem adding it, however there is actually a reason why it was decided not to: when the text-domain is `tgmpa`, the (70+) text strings within TGMPA do not have to be translated by your own translators. TGMPA comes out of the box with translations for 18+ languages already which helps you to internationalize your theme more easily.

Changing the text-domain would undo that benefit and every theme on TF which uses TGMPA would need to ask their translators to translate the TGMPA text strings.
IMHO that is even more of a pain than a few days delay in the theme release.

**Comment by Stephen-Cronin** [comment]
Hi @DJMIMi 

@jrfnl is quite right - we do allow the `tgmpa` text domain on ThemeForest. If you're being rejected for that, you shouldn't be. I've just reminded the team of this. If you are soft rejected again for that reason, then when you're resubmitting, just add a note for the reviewer to check with me or point them to this comment. 

Thanks for your patience.

**Comment by milutinjaric** [comment]
Hi Stephen.

Thanks. Will do. 

Regards.
