### ISSUE TITLE
Question - Visual Composer won't upgrade unless deactivated - Using TGMPA in plugin

### ISSUE THREAD

**Issue by sflwa** [thomasgriffin/TGM-Plugin-Activation#625]
As my post says I'm using this in a plugin and Visual Composer won't update unless I deactivate the plugin first

There was something in the FAQ but that seemed to be if using this via a theme

Thanks

**Comment by jrfnl** [comment]
@sflwa Presuming you have a VC developers license, the principle of it is the same, whether you are including it with a theme or a plugin.

Please have another look at the [FAQ](http://tgmpluginactivation.com/faq/updating-bundled-visual-composer/) and the linked VC documentation page as I suspect that that solution will work for you as well.
