### ISSUE TITLE
Fatal Error with tgmpa and plugin installation

### ISSUE THREAD

**Issue by esaria** [thomasgriffin/TGM-Plugin-Activation#628]
Hi, 
I installed a plugin called Tweet Old post in my Wordpress theme (geodirectory) and it crashed my site and I received this fatal error:

Fatal error: Cannot redeclare tgmpa_load_bulk_installer() (previously declared in //wp-content/plugins/tweet-old-post-pro/inc/lib/dependencies/class-tgm-plugin-activation.php:3154) in //wp-content/themes/GeoDirectory_framework/admin/tgm/class-tgm-plugin-activation.php on line 2204

I contacted the plugin support and they told me to: 

"Please contact your theme developer and tell them update their TGMPA plugin to the latest version so your theme could work with our plugin."

So I contacted my theme developer who told me:

I've just checked with our developer and he mentioned that you have to contact the TGMPA support regarding the issue since the error message you received contains an "error message with something about TGMPA.

Now I am contacting you.  Can you please assist? I'm not technical but I think the TGMPA plugin needs to be updated???

Thank you.

**Comment by jrfnl** [comment]
I'm so sorry that everyone is pointing to someone else. Let me try and help you.

First off: Plugin support was correct. This **_is_** an issue with your theme and the theme developer should update the version of the TGMPA library they ship with the theme.

Please _do_ tell your theme developer this as this might also cause issues for other users of the theme - you can point them to this issue when you do and I'll add some instruction at the bottom specifically for the theme developer.

In the mean time, you can fix this yourself by applying the upgrade to your installation.

As the _Tweet Old Post Pro_ plugin is a commercial plugin, I can't check what version of TGMPA they currently include, but just to be sure, let's update the TGMPA version in both the theme as well as in the plugin.

Steps:
- [Download the current version](https://github.com/TGMPA/TGM-Plugin-Activation/archive/2.6.1.zip) of the library.
- Unzip the file and
- Copy/upload (via FTP) just the `class-tgm-plugin-activation.php` file to the `/wp-content/themes/GeoDirectory_framework/admin/tgm/` and the `/wp-content/plugins/tweet-old-post-pro/inc/lib/dependencies/` directory of your website, replacing the existing `class-tgm-plugin-activation.php` file in each of these two directories.
- [Optional] If you like to be able to see the messages and admin page TGMPA generates in a different language, you might also want to upload the complete `/languages` subdirectory which is included in the zip file. You can just drop the complete subdirectory in the same folders I mentioned above.

Once you've done that, all should be fine again.

Hope this helps!

---

### For the theme developer:

Please upgrade the included version of the TGM plugin activation class you use in your theme(s) to the latest version (2.6.1). From what I can tell, you are currently using version v2.4.0 which is **very** old, out-of-date, buggy and has some minor - but well publicized - security issues.

If you download a fresh copy of TGMPA using the [Custom TGMPA Generator](http://tgmpluginactivation.com/download/), it will serve you with a customized download of TGMPA which will pass the Theme Check rules used by WordPress.org and ThemeForest.

Also - be aware of some minor changes to the TGMPA configuration options in v2.5.0. See the [changelog](https://github.com/TGMPA/TGM-Plugin-Activation/blob/master/CHANGELOG.md) for more information or the [Configuration](http://tgmpluginactivation.com/configuration/) page for more detail on the current options.

**Comment by esaria** [comment]
Thank you for your responses.  I'll go back to the "chain."

**Comment by jrfnl** [comment]
@esaria Just checking: did you manage to fix this for your install with the steps I provided ?

**Comment by esaria** [comment]
I haven't done that yet, I was going to approach the developer of the theme first, but I'll try it now.

**Comment by esaria** [comment]
I've downloaded the file/unzipped, but I'd better wait til later tonight to try it out when web traffic is lower.
I'll update you tomorrow.

**Comment by esaria** [comment]
Hi,

All good to go.

Thank you for your help.

**Comment by jrfnl** [comment]
Glad to hear. I'll close the issue in that case.

**Comment by esaria** [comment]
Thank you.

**Comment by Berny-Design** [comment]
I got the same problem!!
Thank you very much!

**Comment by riyasrahman** [comment]
Dear all
i am also facing the same issue. i have 10 plugins to install via TGMPA but the installation get stooped in 7.
