### ISSUE TITLE
Required Conditions Fulfilled

### ISSUE THREAD

**Issue by Aternus** [thomasgriffin/TGM-Plugin-Activation#638]
Is there a way to check whether all required plugins have been installed before continuing with the theme code execution?

I would like to halt (gracefully) and show an error message on the front end for users without the required plugins.

**Comment by jrfnl** [comment]
Duplicate of #484 #485 and #550.

You can use `TGM_Plugin_Activation::get_instance()->is_tgmpa_complete()`, but as this method is meant for internal use, it will report `false` if there are plugins which need updates or optional plugins which haven't been installed.

Alternatively - in your case this might be the better option - you can pass your list of required plugins through a `foreach()` checking each with the WP native `is_plugin_active()`.

Hope this helps.
