### ISSUE TITLE
Update admin notices not visible

### ISSUE THREAD

**Issue by danyj** [thomasgriffin/TGM-Plugin-Activation#646]
Just changed required plugin version to test and the only notice I see is in plugin itself. 
Admin notices do not appear. Cleared cache tried different browser

![screenshot_23](https://cloud.githubusercontent.com/assets/2340172/22929386/bf6d609a-f2bb-11e6-84d6-512d9629c0fb.png)

tgmpa plugin   array

        array(
            'name'               => 'Assign Widgets', // The plugin name.
            'slug'               => 'assign-widgets', // The plugin slug (typically the folder name).
            'source'             => 'https://github.com/Themezly/Assign-Widgets/archive/master.zip', // The plugin source.
            'required'           => true, // If false, the plugin is only 'recommended' instead of required.
            'version'            => '1.0.3', // E.g. 1.0.0. If set, the active plugin must be this version or higher.
            'force_activation'   => false, // If true, plugin is activated upon theme activation and cannot be deactivated until theme switch.
            'force_deactivation' => true, // If true, plugin is deactivated upon theme switch, useful for theme-specific plugins.
        ),

**Comment by jrfnl** [comment]
Could it be that you dismissed the TGMPA notice before ?

**Comment by danyj** [comment]
I disabled the theme , reactivated and notice showed , so seems like I did dismiss it . not sure if notices are in DB or cache , if DB than it would make sense not to see it in another browser , if cache than it makes no sense. but I think it is related to https://github.com/TGMPA/TGM-Plugin-Activation/issues/353

**Comment by jrfnl** [comment]
@danyj It's being saved in the database, so yes, #353 is the issue which is open about this.

**Comment by danyj** [comment]
ok , il close this than until other one is fixed
