### ISSUE TITLE
Add possibility to use non zip plugins

### ISSUE THREAD

**Issue by roopemerikukka** [thomasgriffin/TGM-Plugin-Activation#654]
I write quite a lot of plugins that are just a single `.php` files. In example I do most of the custom post types as plugins so that they can be activated/deactivated for debugging purposes. It would be nice to be able to include those to the theme without always zipping them, so I'm suggesting to add support for plugins that are just single `.php` files.

**Comment by jrfnl** [comment]
Thanks for your suggestion.

TGMPA uses the plugin installation/update mechanism as is build into WP core. This does currently not allow for installation of non-zipped plugins.
I suggest you open a [feature request](https://core.trac.wordpress.org/) for this with WP core.

**Comment by roopemerikukka** [comment]
Okay thanks, I'll check that!
