### ISSUE TITLE
Hook / Ajax Call

### ISSUE THREAD

**Issue by heldervilela** [thomasgriffin/TGM-Plugin-Activation#659]
Hello
I love this plugin, however I want to create a custom page where I can install or update my plugins. But for that I need a hook (action) or ajax action.

Is there anything available to do this?

Thank you.

**Comment by jrfnl** [comment]
Hi @Lder, that's not how TGMPA is supposed to work. TGMPA does not differentiate between the plugins *you* register as required/recommened and the plugins another plugin registers as required/recommended, so there is no way to just get "your" plugins and showing a custom page with plugins which are required/recommended by other plugins mixed in, is probably not your intention.

**Comment by heldervilela** [comment]
Hello
I'm sorry but I see that I did not explain myself well.
What I want is: call a method ( giving the plugin name that exist on tgm list ) and it performs the necessary functions to install or activate this plugin.

If I call this url for exemple:
`... / wp-admin / themes.php? Page = tgmpa-install-plugins & plugin = plugin-name & tgmpa-install = install-plugin & tgmpa-nonce = nonceXXXX`

I can do this, but it does not seem to be the right way.
