### ISSUE TITLE
Incorrect type of source determination

### ISSUE THREAD

**Issue by pasqualevitiello** [thomasgriffin/TGM-Plugin-Activation#664]
Hey guys,

`get_template_directory_uri` makes `External Source` display, while it should say `Pre-Packaged`.

Cheers!

![screen-shot-2017-05-26-at-10 20 24](https://cloud.githubusercontent.com/assets/2683512/26501071/b06be77a-4238-11e7-91f8-3bbc384d6792.jpg)

**Comment by jrfnl** [comment]
No, for pre-packaged plugins you should use `get_template_directory()` as TGMPA expects a path. If it is given a URL it will download the file instead of directly accessing it through the file system, which is why it is considered an external source.
