### ISSUE TITLE
Install required plugins on Wordpress 4.8

### ISSUE THREAD

**Issue by kadirzdev** [thomasgriffin/TGM-Plugin-Activation#668]
https://i.hizliresim.com/nWkGv1.jpg

When i try "install required plugins" on Wordpress 4.8 this error coming up!
No problem another wordpress version etc. 4.7, 4.6 ..

Thank you!

**Comment by jrfnl** [comment]
@buolur I've just had a quick look, but that shouldn't happen with any of the recent versions of TGMPA. Could you check which version of TGMPA is being used by the theme/plugin using it on your install ?

Most likely it will be a very old - pre v2.5.0 - version and the issue will be solved by the theme/plugin upgrading the TGMPA version they include.

**Comment by kadirzdev** [comment]
Problem solved. Simply it's not problem. It's about "Wampserver". I tryed online and no problem. Sorry.
Thank you!

**Comment by jrfnl** [comment]
@buolur Thanks for getting back to us & glad to hear your issue is solved.

**Comment by xrsx** [comment]
I m getting a same bug  during "install required plugins" and it's just with wp 4.8. Tested with tgmpa 2.6.1 on local host and server (themeforest & wordpress.org pack). Always this message:

"Warning: sprintf(): Too few arguments in /home/xxx/public_html/wp-admin/includes/class-bulk-upgrader-skin.php on line 154"

Thank you!

**Comment by GaryJones** [comment]
@direkte Since the OP has said this was down to Wampserver, please open a new report for yours (even if the error message is the same).
