### ISSUE TITLE
TGMPA plugin installation notices not showing

### ISSUE THREAD

**Issue by Muazhesam** [thomasgriffin/TGM-Plugin-Activation#677]
After Theme Installation and activation there should be a notice about installing plugins on that theme.But i am not getting that message/notice. Look at the below picture

![Image of Yaktocat](https://i.stack.imgur.com/9dN9k.png)

But still there is plugins to install and activate

![Image of Yaktocat](https://i.stack.imgur.com/nbiVX.png)

How can i solve this problem?

**Comment by jrfnl** [comment]
Have you previously had a theme/plugin installed which also used TGMPA and dismissed the admin notice ? If so, that is most likely the problem as the admin notice is currently not unique to your theme/plugin.

**Comment by Muazhesam** [comment]
I have tried on new wp install on new domain..but result zero..

**Comment by jrfnl** [comment]
What setting have you got for `has_notices` in the `$config` array ?

**Comment by Muazhesam** [comment]
'has_notices'  => true,

**Comment by jrfnl** [comment]
I presume you have access to the database: could you do a search in the `usermeta` table for `meta_key LIKE 'tgmpa_dismissed_notice%'` ?
If it is truly a fresh install, that key should not exist in the usermeta table.
If it does.... that's the problem and only goes to show that the admin notice **was** dismissed before.

You can delete those rows from the table in that case and the admin notice should start showing up again.

**Comment by Muazhesam** [comment]
Does not exists!
![screenshot_37](https://user-images.githubusercontent.com/12009802/28216694-5fde62de-68d4-11e7-9911-d752ca098cf4.png)

![screenshot_38](https://user-images.githubusercontent.com/12009802/28216765-951dfc3e-68d4-11e7-81ad-8306a30a5584.png)

**Comment by jrfnl** [comment]
Oh dear. Ok, do you know of any plugins on your website which also use TGMPA ?

**Comment by Muazhesam** [comment]
Solved that dude..Thanks a lot

**Comment by GaryJones** [comment]
@Muazhesam Can you please share your solution so future readers know what to try?

**Comment by jrfnl** [comment]
What @GaryJones said. Oh and...

> Solved that **dude**

Eh... I presume you mean _Thank you for your help, fair lady_ ?
