### ISSUE TITLE
[Question] Wp Favs Integration

### ISSUE THREAD

**Issue by timersys** [thomasgriffin/TGM-Plugin-Activation#687]
Hi Guys, just wanted to ask before getting my hands dirty if you would accept a PR to add wp favs integration to the TGM plugin so users could add a [simple token key](https://wpfavs.com/wpfavs/editors-choice) instead of the bundled plugins zips.
That way theme authors could considerably reduce the size of themes.

I'm currently using a custom coded version of TGM in  the [Wp Favs plugin](https://wordpress.org/plugins/wpfavs/) but adding native support to the plugin will benefit lot of users.

That token mentioned early return direct download urls that can be passed to TGM. Example from the list above can be found in https://wpfavs.com/api/v1/wpfav/3b871fb19229696af32307da785d66e0

Regards

**Comment by GaryJones** [comment]
If you can do the PR, and the end result is that it doesn't negatively affect anyone not using wpfavs.com, then we can definitely consider merging it. Thanks!

**Comment by timersys** [comment]
Great, that's all I needed to hear. Thanks
