### ISSUE TITLE
Can this be removed? "REQUIRED: Zip file found. Plugins are not allowed in themes." Or make it INFO

### ISSUE THREAD

**Issue by cristianstan** [thomasgriffin/TGM-Plugin-Activation#711]
`REQUIRED: Zip file found. Plugins are not allowed in themes. The zip file found was plugin1-name.zip plugin2-name.zip .`

Right now, ThemeForest requirements (reviewers) says that all bundled plugins to be included into the folder of the theme and then installed via TGMPA as pre-packaged. (Basically you are not allowed to have your custom plugins into a repository or on your website) 👎 

So, Is there any way to get rid of this REQUIRED field? Or maybe, as a suggestion, to make the REQUIRED -> INFO. 🥇 

Reviewers are providing Rejections because the ThemeCheck plugins generates logs like this one. 

Looking forward to a reply,
- Cristian

**Comment by jrfnl** [comment]
Hi Cristian, that sounds to me like a question you should ask the ThemeCheck plugin,... ? I don't know what you expect us to do about it.

**Comment by cristianstan** [comment]
You are right. Sorry about this :+1:

**Comment by jrfnl** [comment]
No problem. ;-)
