### ISSUE TITLE
Certain Wordpress.org plugins don't load

### ISSUE THREAD

**Issue by stickypages** [thomasgriffin/TGM-Plugin-Activation#726]
I setup these 2 plugins from the Wordpress.org site
But they will not show in the list. I'm not sure why this is the case. I have many other plugins listed, but these do not. Thoughts?
`array(
				'name'     => 'Query Monitor',
				'slug'     => 'query-monitor',
				'required' => false,
			),
			array(
				'name'     => 'Better Search Replace',
				'slug'     => 'better-search-replace',
				'required' => false,
			),`

**Comment by jrfnl** [comment]
Just checking: would these plugins happen to be installed on your test site already ?

**Comment by stickypages** [comment]
I see, yes, it was installed and ACTIVATED, which didn't show in the list. If I de-activate them, they showed up in the list. Alright thanks, sorry about that.
