### ISSUE TITLE
Maybe wrong text for "notice_cannot_install"

### ISSUE THREAD

**Issue by ghost** [thomasgriffin/TGM-Plugin-Activation#731]
Hello,

I was reviewing our overrides to use the language pack instead and our french translation is like this (ie. you dont have the rights to install..).

```
			'notice_cannot_install'           => _n_noop(
				'Vous n’avez pas les droits nécessaires pour installer l’extension %1$s.',
				'Vous n’avez pas les droits nécessaires pour installer les extensions %1$s.',
				'platform-shell-theme'
			)
```

But the current texte source is defined like this 

`notice_cannot_install_activate'  => __( 'There are one or more required or recommended plugins to install, update or activate.', 'tgmpa' ),`

If I look at the code is seems like the message should be about the missing rights to to the operation, no a generic message that there are plugins to install, update or activate.

Maybe a known issue?

I will keep my override temporarily!

**Comment by jrfnl** [comment]
@eric-gagnon If I remember correctly, that notice is usually combined with a second phrase asking to inform an admin.
If that's not the case, this would definitely need to be reviewed and suggestions for alternative phrasing would be welcome.

**Comment by ghost** [comment]
Ah, ok I get it, it make sense, same issue but the message is a bit more user friendly.
I’ll get rid of that override in our code.
I close, thanks!
