### ISSUE TITLE
Themes/Plugin Conflict

### ISSUE THREAD

**Issue by raphcadiz** [thomasgriffin/TGM-Plugin-Activation#735]
I'm using TGMPA on my plugin to support installation of add-ons. Everything was working fine until on of the site's theme it was installed is also using TGMPA.

The registered menu is not correct anymore and it follows the one on theme registered on the theme instead of the one below.
```
'parent_slug'  => 'edit.php?post_type=g2pdf_merge',
'capability'   => 'manage_options',
```

The other required theme's plugin is now showing on my add-ons list

![install gravity2pdf add-ons](https://user-images.githubusercontent.com/10813136/37872299-6db9314c-3037-11e8-825a-4f4b1c128d5f.png)

Any workaround for this?

**Comment by GaryJones** [comment]
You've wrongly assumed that your plugin is the only one that's using TGMPA. If your plugin is doing something that makes it display in a different position (apparently in your System Check) tab, then this isn't default behaviour.

**Comment by raphcadiz** [comment]
@GaryJones exactly my point. I didn't realize that a theme may also be using TGMPA. Now what I am asking is there a way that I can create another menu item base on the declaration of my plugin and display the plugins that I added on items.
So basically just another instance of TGMPA

**Comment by jrfnl** [comment]
The whole point of TGMPA is to have *one* page from which to install all dependencies from both plugins as well as the theme, so having another instance of TGMPA would go against the principle for which it was build.

**Comment by GaryJones** [comment]
You could try putting your TGMPA into its own namespace, renaming the class, any globals etc.

**Comment by Oxibug** [comment]
TGMPA with unique namespace to be included into plugins [TGMPA uses Namespace](https://github.com/Oxibug/tgmpa-ns)

And TGMPA with unique classes working with themes [TGMPA in Classes](https://github.com/Oxibug/tgmpa-unique-cls) 

Both working together simultaneously in the same site whereas both are prefixed and you will see notifications separately and each one can be dismissed separately.

It helped me a lot, Hope it help you.
