### ISSUE TITLE
PHP Warning when installing plugin massively.

### ISSUE THREAD

**Issue by franzarmas** [thomasgriffin/TGM-Plugin-Activation#756]
I have activated `define ('WP_DEBUG', true);` in the wp-config.php and when I install several plugins at once, it shows me warnings ..

![screencapture](https://user-images.githubusercontent.com/36080351/43678643-ae1ab730-97dc-11e8-82cb-c8a71d82be4e.png)

**Comment by jrfnl** [comment]
Closing as duplicate of #669 which was fixed by PR #670. The fix will be in the next release of TGMPA.
