### ISSUE TITLE
I can't make my own textdomain name,

### ISSUE THREAD

**Issue by asufian97** [thomasgriffin/TGM-Plugin-Activation#767]
when i clicked what they say..
Failed to retrieve TGMPA: Error: Ajax error for ../releases/TGM-Plugin-Activation-2.6.1.zip : 204 Intercepted by the IDM Advanced Integration

**Comment by jrfnl** [comment]
That is not a TGMPA issue, but an issue with your download manager: https://www.internetdownloadmanager.com/register/new_faq/bi19.html
