### ISSUE TITLE
Load own plugin parameters?

### ISSUE THREAD

**Issue by xmon** [thomasgriffin/TGM-Plugin-Activation#773]
Is it possible to indicate configuration parameters after or during the installation of a plugin?

thanks.

**Comment by jrfnl** [comment]
@xmon Could you explain a bit more what you are trying to archive ? What is the use case ?

**Comment by jrfnl** [comment]
Closing for lack of response.
If this is still an issue, please provide the additional information requested and we can reopen the issue.
