### ISSUE TITLE
 Uncaught Error: Cannot unset string offsets in vendor/tgm-plugin-activation/class-tgm-plugin-activation.php:575

### ISSUE THREAD

**Issue by jeremiahsherrill** [thomasgriffin/TGM-Plugin-Activation#775]
It refers to this

		/**
		 * Remove the 'Activate' link on the WP native plugins page if the plugin does not meet the
		 * minimum version requirements.
		 *
		 * @since 2.5.0
		 *
		 * @param array $actions Action links.
		 * @return array
		 */
		public function filter_plugin_action_links_activate( $actions ) {
			unset( $actions['activate'] );

			return $actions;
		}

Not quite sure what this means.  Only happens on certain themes.  Prevents wordpress plugins from finishing loading.

**Comment by jrfnl** [comment]
@jeremiahsherrill That is weird as this is filtering default WP functionality. The only thing I can think of at the moment, is another plugin/theme interferring and incorrectly filtering the `$actions`.

`$actions` should be an array and if a plugin/theme filters it, it should return an array.

Based on the error message, some plugin/theme is returning a string instead.

The short of it, is that some other plugin/theme appears to be _doing it wrong_, but without more information on which plugins/themes you have running on which version of WP, there is no way for us to determine the culprit.

I suggest you install the [Debug Bar plugin](https://wordpress.org/plugins/debug-bar/) together with the 
[Debug Bar Actions and Filters Addon](https://wordpress.org/plugins/debug-bar-actions-and-filters-addon/) and check what other plugins/themes are hooked into the `plugin_action_links_....` filters.

**Comment by jeremiahsherrill** [comment]
Will look into thanks.

**Comment by jrfnl** [comment]
Closing for lack of response.
If this is still an issue, please provide the additional information requested and we can reopen the issue.
