### ISSUE TITLE
TGMPA is not installing the specified version of plugins

### ISSUE THREAD

**Issue by lwxbr** [thomasgriffin/TGM-Plugin-Activation#779]
The plugin is not installing the version I specified in config file. Take WooCommerce as example:

```
...
        array(
            'name' => 'WooCommerce',
            'slug' => 'woocommerce',
            'version' => '3.4.7',
            'required' => true,
        ),

...
```

Then when I download the plugins and activate, comes the latest version of WooCommerce (3.6.4 at day of today).

**Comment by jrfnl** [comment]
As per the documentation, `version` = minimum version. In other words, TGMPA works exactly as advertised.

Ref: http://tgmpluginactivation.com/configuration/

**Comment by lwxbr** [comment]
@jrfnl, Ok. Sorry. I didn't knew about it. But I think that could be an improvement for the TGMPA. I'm able to help with this issue. What I have in mind: create an option in TGMPA that will allow this feature of strict version like ```strict_version: true```, so the TGMPA will download that version in specific, what you think about that? I will implement this feature and send you a pull request, deal partner? 👍 👍 👍

**Comment by lwxbr** [comment]
https://github.com/TGMPA/TGM-Plugin-Activation/pull/780
