### ISSUE TITLE
How to Instal Redux Plugin With TGM Plugin

### ISSUE THREAD

**Issue by bobbykumar1** [thomasgriffin/TGM-Plugin-Activation#790]
plugin bundled with a theme its not allow in WordPress when i theme upload

```php
        array(
            'name'               => 'TGM Example Plugin', // The plugin name.
            'slug'               => 'tgm-example-plugin',
            'source'             => get_stylesheet_directory() . '/lib/plugins/redux-framework.zip', // The plugin source.
            'required'           => true,
            'external_url'       => '',
        ),
```

Downloading installation package from https://github.com/bobbykumar1/redux-framework/blob/master/redux-framework.zip…

Unpacking the package…

The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature

```php
  array(
            'name'               => 'Redux Framework',
            'slug'               => 'redux-framework',
            'source'             => 'https://github.com/bobbykumar1/redux-framework/blob/master/redux-framework.zip',
            'required'           => true,
            'external_url'       => 'https://github.com/bobbykumar1/redux-framework/blob/master/redux-framework.zip',
            'force_activation'   => true,
        ),
```

**Comment by jrfnl** [comment]
That's because the URL doesn't actually point to a zip file for download.

Go to the URL yourself and see that no zip is offered for download, it just displays the Github page for that file.

Try this: https://github.com/bobbykumar1/redux-framework/raw/master/redux-framework.zip

**Comment by bobbykumar1** [comment]
can you guide me how create you url like this its very helpfull for me 

 https://github.com/bobbykumar1/redux-framework/raw/master/redux-framework.zip

**Comment by jrfnl** [comment]
@bobbykumar1 If you go to this page: https://github.com/bobbykumar1/redux-framework/blob/master/redux-framework.zip (which shows the GH page, but doesn't start a download), you will see a "download" button, copy the link which that button links to and you have the correct URL.

![image](https://user-images.githubusercontent.com/663378/79875545-1a985c00-83ea-11ea-85f7-f68b08f41d9b.png)

**Comment by bobbykumar1** [comment]
thankyou so much

**Comment by jrfnl** [comment]
@bobbykumar1 Can we close this issue then ?

**Comment by bobbykumar1** [comment]
there is issue with repositories can we make it private ?

**Comment by jrfnl** [comment]
@bobbykumar1 What do you mean ?

**Comment by bobbykumar1** [comment]
https://github.com/bobbykumar1/redux-framework/raw/master/redux-framework.zip
![Screenshot (27)](https://user-images.githubusercontent.com/60466926/79884730-23515800-8413-11ea-94ea-1bea163417d9.png)

**Comment by bobbykumar1** [comment]
https://prnt.sc/s3epg5

**Comment by jrfnl** [comment]
Well, I'm still not sure what your question is now, but the intend of the feature when developed was to allow for tagged release zips of plugins which are being developed on GH to be installed via TGMPA.
Not for random zips which are part of the repo file system to be installable.

**Comment by bobbykumar1** [comment]
when i open this link  google chrome tab file are download but incognito mode show page not found but link are right 

https://github.com/bobbykumar1/redux-framework/raw/master/redux-framework.zip
