### ISSUE TITLE
Dynamic Content for Elementor

### ISSUE THREAD

**Issue by ghost** [thomasgriffin/TGM-Plugin-Activation#801]
Hello :)

I downloaded the plugin for the dynamic content for elementor. However, it says I require a licence key. Is this something you may be able to help me with? 

It was downloaded via your platform. :)

Thank you

**Comment by jrfnl** [comment]
@educately TGMPA is not a platform, but a library to allow themes and plugins to indicate dependencies/recommendations for other plugins.

Themes/Plugins can set the download location themselves. This is outside of our control and no plugins are hosted by TGMPA.

I suggest you contact the support desk of elementor.
