### ISSUE TITLE
Add option to place INSTALLed plugins to mu-plugins folder

### ISSUE THREAD

**Issue by wpsmith** [thomasgriffin/TGM-Plugin-Activation#83]
In light of moving core functionality to a plugin (see links below), is it possible or a good idea to have the ability in the plugin activation class to move an installed plugin to mu-plugins folder?

WP Candy: http://wpcandy.com/teaches/how-to-create-a-functionality-plugin
Bill: http://www.billerickson.net/core-functionality-plugin/
Otto: http://ottopress.com/2011/creating-a-site-specific-snippets-plugin/
Justin Tadlock: http://justintadlock.com/archives/2010/12/30/wordpress-theme-function-files

**Comment by jimmyandrade** [comment]
My thoughts on the TGM as must-use plugin: when we set which plug-ins are required or recommended for a theme, the register function will continue being part of the subject code. TGM will keep looking for registering action coded on theme to set if the plugin is either required/recommended.

Regarding the problem of WordPress load only the mu-plugins that have a .php file in the folder itself, there is already a way around this. There's an autoloader that enables standard plugins to be required just like must-use plugins. It's [Bedrock Autoloader](https://github.com/roots/bedrock/blob/master/web/app/mu-plugins/bedrock-autoloader.php), from @roots.

The autoloaded plugins are included during mu-plugin loading. An asterisk (*) next to the name of the plugin designates the plugins that have been autoloaded.
